version: '3.8'

services:
  fastapi:
    image: stephenhuo/fastapi:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    
  streamlit:
    image: stephenhuo/streamlit:dev
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi